const mongoose=require('mongoose');
const PaymentLink=mongoose.model('PaymentLink',new mongoose.Schema({
  linkId:{type:String,unique:true},
  orderId:{type:String,unique:true},
  amount:{type:Number,min:1,max:5000},
  description:String,
  status:{type:String,default:'PENDING',index:true},
  paymentUrl:String,
  paymentMethod:{type:String,enum:['UPI','CRYPTO'],default:'UPI',index:true},
  provider:{type:String,default:'zappay',index:true},
  providerPaymentId:String,
  cryptoCurrency:String,
  cryptoAmount:Number,
  discordUserId:String,
  discordUsername:String,
  guildId:{type:String,index:true},
  guildName:String,
  expiresAt:Date,
  paidAt:Date,
  providerStatus:String,
  providerResponse:mongoose.Schema.Types.Mixed
},{timestamps:true}));
const Transaction=mongoose.model('Transaction',new mongoose.Schema({
  orderId:{type:String,unique:true},
  linkId:String,
  amount:Number,
  description:String,
  status:{type:String,default:'PENDING'},
  providerStatus:String,
  provider:{type:String,default:'zappay'},
  paymentMethod:{type:String,enum:['UPI','CRYPTO'],default:'UPI'},
  providerPaymentId:String,
  cryptoCurrency:String,
  cryptoAmount:Number,
  discordUserId:String,
  discordUsername:String,
  guildId:{type:String,index:true},
  guildName:String,
  paidAt:Date,
  providerResponse:mongoose.Schema.Types.Mixed
},{timestamps:true}));
module.exports={PaymentLink,Transaction};
